In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'2.0.3'

In [3]:
df = pd.read_csv("/home/phagun-jain/Downloads/housing.csv")
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [7]:
sh = df.shape
print(f"no of columns: {sh[1]}")

no of columns: 10


In [10]:
df.isnull()
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [11]:
df.ocean_proximity.nunique()

5

In [12]:
df.median_house_value.mean()

206855.81690891474

In [13]:
df.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000   
mean    -119.569704     35.631861           28.639486   2635.763081   
std        2.003532      2.135952           12.585558   2181.615252   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1447.750000   
50%     -118.490000     34.260000           29.000000   2127.000000   
75%     -118.010000     37.710000           37.000000   3148.000000   
max     -114.310000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  \
count    20433.000000  20640.000000  20640.000000   20640.000000   
mean       537.870553   1425.476744    499.539680       3.870671   
std        421.385070   1132.462122    382.329753       1.899822   
min          1.000000      3.000000      1.000000       0.499900   
25%        296.000000    787.000000    280.000000       2.563400   
50%        435.000000   1166.000000    409.000000       3.534800   
75%        647.000000   1725.000000    605.000000       4.743250   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        20640.000000  
mean        206855.816909  
std         115395.615874  
min          14999.000000  
25%         119600.000000  
50%         179700.000000  
75%         264725.000000  
max         500001.000000

In [15]:
df.groupby('ocean_proximity').median_house_value.mean()

ocean_proximity
<1H OCEAN     240084.285464
INLAND        124805.392001
ISLAND        380440.000000
NEAR BAY      259212.311790
NEAR OCEAN    249433.977427
Name: median_house_value, dtype: float64

In [16]:
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [18]:
df.index

RangeIndex(start=0, stop=20640, step=1)

KeyError: "None of ['a'] are in the columns"

In [22]:
df.total_bedrooms.mean()

537.8705525375618

In [24]:
df.total_bedrooms.describe()

count    20433.000000
mean       537.870553
std        421.385070
min          1.000000
25%        296.000000
50%        435.000000
75%        647.000000
max       6445.000000
Name: total_bedrooms, dtype: float64

In [26]:
df.total_bedrooms.isnull().sum()

207

In [39]:
df2 = df["total_bedrooms"].fillna(538)

In [43]:
df2.isnull().sum()

0

In [44]:
df2.mean()

537.8718507751938

In [45]:
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [48]:
df.groupby('ocean_proximity').describe()

longitude                                                 \
                    count        mean       std     min     25%      50%   
ocean_proximity                                                            
<1H OCEAN          9136.0 -118.847766  1.588888 -124.14 -118.50 -118.275   
INLAND             6551.0 -119.732990  1.900950 -123.73 -121.35 -120.000   
ISLAND                5.0 -118.354000  0.070569 -118.48 -118.33 -118.320   
NEAR BAY           2290.0 -122.260694  0.147004 -122.59 -122.41 -122.250   
NEAR OCEAN         2658.0 -119.332555  2.327307 -124.35 -122.02 -118.260   

                                  latitude             ... median_income  \
                      75%     max    count       mean  ...           75%   
ocean_proximity                                        ...                 
<1H OCEAN       -118.0000 -116.62   9136.0  34.560577  ...      5.180500   
INLAND          -117.8400 -114.31   6551.0  36.731829  ...      3.961500   
ISLAND          -118.3200 -118.32      5.0  33.358000  ...      2.833300   
NEAR BAY        -122.1400 -122.01   2290.0  37.801057  ...      5.054425   
NEAR OCEAN      -117.1825 -116.97   2658.0  34.738439  ...      4.837400   

                         median_house_value                                \
                     max              count           mean            std   
ocean_proximity                                                             
<1H OCEAN        15.0001             9136.0  240084.285464  106124.292213   
INLAND           15.0001             6551.0  124805.392001   70007.908494   
ISLAND            3.3906                5.0  380440.000000   80559.561816   
NEAR BAY         15.0001             2290.0  259212.311790  122818.537064   
NEAR OCEAN       15.0001             2658.0  249433.977427  122477.145927   

                                                                   
                      min       25%       50%       75%       max  
ocean_proximity                                                    
<1H OCEAN         17500.0  164100.0  214850.0  289100.0  500001.0  
INLAND            14999.0   77500.0  108500.0  148950.0  500001.0  
ISLAND           287500.0  300000.0  414700.0  450000.0  450000.0  
NEAR BAY          22500.0  162500.0  233800.0  345700.0  500001.0  
NEAR OCEAN        22500.0  150000.0  229450.0  322750.0  500001.0  

[5 rows x 72 columns]

In [49]:
df3  = df[['total_rooms','median_income','population' ]]

In [65]:
df3

total_rooms  median_income  population
0            880.0         8.3252       322.0
1           7099.0         8.3014      2401.0
2           1467.0         7.2574       496.0
3           1274.0         5.6431       558.0
4           1627.0         3.8462       565.0
...            ...            ...         ...
20635       1665.0         1.5603       845.0
20636        697.0         2.5568       356.0
20637       2254.0         1.7000      1007.0
20638       1860.0         1.8672       741.0
20639       2785.0         2.3886      1387.0

[20640 rows x 3 columns]

In [57]:
df3.total_rooms.values
df3.total_rooms.values.size

20640

In [58]:
df3.median_income.values
df3.median_income.values.size

20640

In [60]:
df3.population.values
df3.population.values.size

20640

In [66]:
X = df3.values
X

array([[8.8000e+02, 8.3252e+00, 3.2200e+02],
       [7.0990e+03, 8.3014e+00, 2.4010e+03],
       [1.4670e+03, 7.2574e+00, 4.9600e+02],
       ...,
       [2.2540e+03, 1.7000e+00, 1.0070e+03],
       [1.8600e+03, 1.8672e+00, 7.4100e+02],
       [2.7850e+03, 2.3886e+00, 1.3870e+03]])

In [74]:
XTX = X.dot(X.T)
XTX

array([[  878153.30895504,  7020311.11081528,  1450732.41930648, ...,
         2307788.15284   ,  1875417.54481344,  2897433.88557272],
       [ 7020311.11081528, 56160670.91324196, 11605189.24658036, ...,
        18418967.11238   , 14983296.50037408, 23100921.82872404],
       [ 1450732.41930648, 11605189.24658036,  2398157.66985476, ...,
         3806102.33758   ,  3096169.55101728,  4773564.33502564],
       ...,
       [ 2307788.15284   , 18418967.11238   ,  3806102.33758   , ...,
         6094567.89      ,  4938630.17424   ,  7674103.06062   ],
       [ 1875417.54481344, 14983296.50037408,  3096169.55101728, ...,
         4938630.17424   ,  4008684.48643584,  6207871.45999392],
       [ 2897433.88557272, 23100921.82872404,  4773564.33502564, ...,
         7674103.06062   ,  6207871.45999392,  9679999.70540996]])

In [72]:
y = [950, 1300, 800, 1000, 1300]
y

[950, 1300, 800, 1000, 1300]

In [77]:
ixtx = np.linalg.inv(XTX)

In [78]:
ixtx

array([[-5.51532691e+07,  1.74531179e+07, -7.81954134e+07, ...,
        -2.12436688e+08,  1.66992788e+08, -2.44727385e+07],
       [ 1.27581639e+05,  3.03344948e+05, -9.70622091e+06, ...,
         8.60732654e+05,  2.05205802e+06,  7.56572645e+06],
       [ 5.61723147e+07,  1.62555989e+07, -7.79266847e+07, ...,
        -2.35229177e+08,  7.91411417e+07, -1.00450504e+08],
       ...,
       [-3.55147347e+06, -4.72622767e+05, -4.79504712e+06, ...,
         2.39842950e+05,  2.32981633e+06,  3.48430270e+06],
       [ 1.55624449e+06,  2.04348036e+05, -1.62329859e+06, ...,
        -2.65290334e+06,  2.58034972e+06, -1.29599767e+06],
       [ 7.38561996e+05, -3.09914160e+05, -3.73414885e+05, ...,
         1.10827291e+05, -1.96931635e+06, -2.99485928e+05]])

In [85]:
res = ixtx.dot(X.T)

ValueError: shapes (20640,20640) and (3,20640) not aligned: 20640 (dim 1) != 3 (dim 0)

In [ ]:
w = res.dot(y)

In [ ]:
w